# Org-wide label catalog
# Use the reusable workflow .github/workflows/sync-labels.yml to apply these to repositories.

- name: P0 - Critical
  color: d73a4a
  description: Highest priority; must-have for imminent release; blocks core workflows

- name: P1 - High
  color: d93f0b
  description: Important and targeted soon

- name: P2 - Medium
  color: fbca04
  description: Valuable; schedule as capacity allows

- name: P3 - Low
  color: c2e0c6
  description: Nice-to-have; low urgency

- name: "type: feature"
  color: 0e8a16
  description: New functionality or enhancement request

- name: "status: backlog"
  color: e4e669
  description: Triaged but not yet scheduled

- name: "status: planned"
  color: 0366d6
  description: Accepted and scheduled for upcoming work

- name: "status: in progress"
  color: 1d76db
  description: Currently being implemented

- name: "status: blocked"
  color: b60205
  description: Cannot proceed due to a dependency or issue

- name: "needs: discussion"
  color: d4c5f9
  description: Requires further product/engineering discussion
